export const ITEMS_LIST_REQUEST ="ITEMS_LIST_REQUEST";
export const ITEMS_LIST_SUCCESS ="ITEMS_LIST_SUCCESS";
export const ITEMS_LIST_FAIL ="ITEMS_LIST_FAIL";


export const ITEMS_CREATE_REQUEST ="ITEMS_CREATE_REQUEST";
export const ITEMS_CREATE_SUCCESS ="ITEMS_CREATE_SUCCESS";
export const ITEMS_CREATE_FAIL ="ITEMS_CREATE_FAIL";


export const ITEMS_UPDATE_REQUEST ="ITEMS_UPDATE_REQUEST";
export const ITEMS_UPDATE_SUCCESS ="ITEMS_UPDATE_SUCCESS";
export const ITEMS_UPDATE_FAIL ="ITEMS_UPDATE_FAIL";   


export const ITEMS_DELETE_REQUEST ="ITEMS_DELETE_REQUEST";
export const ITEMS_DELETE_SUCCESS ="ITEMS_DELETE_SUCCESS";
export const ITEMS_DELETE_FAIL ="ITEMS_DELETE_FAIL";   